spring:
  datasource:
    url: jdbc:h2:mem:previred
    username: previredb
    password: previ123_
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  api-docs:
    path: /api-docs

security:
  jwt:
    secret-key: 03fa7e6f1493c71c0ea591f8fc057a08fcd04a4720f8e8cbd0a756c7272e00b9
    expiration-time: 300000